[package]
name = "gsm7"
description = "GSM-7 (aka GSM 03.38 or 3GPP 23.038) encoding and decoding in Rust"
version = "0.2.0"
authors = ["jbg <jbg@dtmf.io>"]
edition = "2018"
license = "MIT"
readme = "README.md"

[dependencies]
bitstream-io = "0.8.4"
